# GitHub will display these funding options on the repository page.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [TheInfamousToTo]
buy_me_a_coffee: TheInfamousToTo
